apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxpod
spec:
  selector:
    matchLabels:
      app: nginxpod
  replicas: 1
  template:
    metadata:
      labels:
        app: nginxpod
    spec:
      containers:
      - name: nginxcontainer
        image: nginx
        ports:
        - containerPort: 80
