apiVersion: v1
kind: Service
metadata:
  name: paraloyalpod
  labels:
    app: paraloyalpod
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: paraloyalpod
  type: LoadBalancer